version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=lumen
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysqlpass
    command: bash -c "cp .env.example .env && composer install && apache2-foreground"
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
      - MYSQL_DATABASE=lumen

  